export const RPC_PROVIDER_THROUGHPUT_GROWTH = 660;
export const RPC_PROVIDER_THROUGHPUT = RPC_PROVIDER_THROUGHPUT_GROWTH;
export const CU_PRICE_ETH_GET_TRANSACTION_RECEIPT = 15;
export const MAX_ETH_GET_TRANSACTION_RECEIPT_REQUESTS_PER_SECOND =
  (0.92 * RPC_PROVIDER_THROUGHPUT) / CU_PRICE_ETH_GET_TRANSACTION_RECEIPT;
